vertexai:
  project: "hackathon-420406"
  location: "us-central1"
  model_name: "gemini-1.5-pro-preview-0409"
prompts_file_path: "prompts/prompts_v3.yml"
log_dir: "logs"
image_gen_model: "imagegeneration@006"
